server:
  port: 8082

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 暴露服务状态信息
management:
  endpoints:
    web:
      exposure:
        include: "*"